/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mmateusa.petshop.screens.forms;
import com.mmateusa.petshop.dao.*;
import com.mmateusa.petshop.Petshop;
import com.mmateusa.petshop.screens.AdmDashboard;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
/**
 *
 * @author Mateus
 */
public class AnimalForm extends javax.swing.JPanel {

    /**
     * Creates new form AnimalForm
     */
    
    private AdmDashboard admDashboard;
    private JDialog dialog;

    public AnimalForm(AdmDashboard admDashboard, JDialog dialog) {
        this.admDashboard = admDashboard;
        this.dialog = dialog;
        initComponents();
        DefaultComboBoxModel tipos = (DefaultComboBoxModel) tipoInpt.getModel();
        List<TiposAnimais> ta = Petshop.entityManager.createQuery("SELECT ta FROM TiposAnimais ta").getResultList();
        for (int i = 0; i < ta.size(); i++) {
            tipos.addElement(ta.get(i).getId() + "-" + ta.get(i).getTipo());
        }
        
        DefaultComboBoxModel donos = (DefaultComboBoxModel) donoInpt.getModel();
        List<Usuarios> u = Petshop.entityManager.createQuery("SELECT u FROM Usuarios u").getResultList();
        for (int i = 0; i < u.size(); i++) {
            donos.addElement(u.get(i).getId() + "-" + u.get(i).getNome());
        }
    }
    
    public AnimalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeInpt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tamanhoInpt = new javax.swing.JSpinner();
        pesoInpt = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        idadeInpt = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tipoInpt = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        donoInpt = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tamanho (cm):");

        jLabel1.setText("Nome:");

        tamanhoInpt.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        pesoInpt.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel5.setText("Peso (Kg):");

        idadeInpt.setModel(new javax.swing.SpinnerNumberModel());

        jLabel6.setText("Idade:");

        jLabel7.setText("Tipo:");

        jLabel9.setText("Dono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 221, Short.MAX_VALUE))
                            .addComponent(nomeInpt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(177, 177, 177))
                            .addComponent(tamanhoInpt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(pesoInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idadeInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tipoInpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(donoInpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeInpt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tamanhoInpt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesoInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idadeInpt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(tipoInpt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donoInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TiposAnimais tipo = Petshop.entityManager.find(TiposAnimais.class, Integer.parseInt(tipoInpt.getSelectedItem().toString().split("-")[0]));
        Usuarios dono = Petshop.entityManager.find(Usuarios.class, Integer.parseInt(donoInpt.getSelectedItem().toString().split("-")[0]));
        Petshop.entityManager.getTransaction().begin();
        Animais a = new Animais(nomeInpt.getText(), (double) tamanhoInpt.getValue(), (double) pesoInpt.getValue(), (int) idadeInpt.getValue(), tipo, dono);
        Petshop.entityManager.persist(a);
        Petshop.entityManager.getTransaction().commit();
        admDashboard.getAnimals();
        dialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> donoInpt;
    private javax.swing.JSpinner idadeInpt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeInpt;
    private javax.swing.JSpinner pesoInpt;
    private javax.swing.JSpinner tamanhoInpt;
    private javax.swing.JComboBox<String> tipoInpt;
    // End of variables declaration//GEN-END:variables
}
